Book/urls.py
from django.contrib import admin
from django.urls import path,include
import py_app
from py_app import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.pyspiders,name="pyspiders"),
    path('title/',views.title,name="title"),
    path('index/',views.index,name="index"),
    path('python/',views.python,name="python"),
    path('django/',views.django,name="django"),
    path('webtech/',include('py_app.urls')),
    path('sql',views.sql,name="sql"),
]

py_app/urls.py
from django.urls import path
from py_app import views
app_name='py_app'
urlpatterns=[
    path('html',views.html,name="html"),
    path('css',views.css,name="css"),
    path('js',views.js,name="js"),
]

py_app/models.py
from django.db import models

# Create your models here.

py_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
def pyspiders(request):
    return HttpResponse("<marquee><h1>Welcome to Pyspiders Library........!!</h1></marquee>")
def title(request):
    return HttpResponse("<center><h1>Python Full-Stack Development</h1></center>")
def index(request):
    return HttpResponse("<center><h1>python, Django, Html5, Css3, JS, SQL</h1></center>")
def python(request):
    return render(request,'python.html')
def django(request):
    return render(request,'django.html')
def html(request):
    return render(request,'html.html')
def css(request):
    return render(request,'css.html')
def js(request):
    return render(request,'js.html')
def sql(request):
    return render(request,'sql.html')

templates/css.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>css</title>
</head>
<body><center>
    <h1>welcome to css</h1>
    <a href="https://en.wikipedia.org/wiki/Cascading_Style_Sheets">about Css</a>
    </center>

    <p> Select Language below :</p>
    <a href="{% url 'python' %}">Python Syllabus</a>
    </br>
    <a href="{% url 'django' %}">django Syllabus</a>
    </br>
    <a href="{% url 'py_app:html' %}">Html Syllabus</a>
    </br>
    <a href="{% url 'py_app:js' %}">Java Script Syllabus</a>
    </br>
    <a href="{% url 'sql' %}">SQL Syllabus</a> 
    
</body>
</html>

templates/django.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>django</title>
    
</head>
<body><center>
    <h1>welcome to django</h1>
    <a href="https://en.wikipedia.org/wiki/Django_(web_framework)">about Django</a>
    </center>

    <p>select language below: </p>
    <a href="{% url 'python' %}">Python Syllabus</a>
    </br>
    <a href="{% url 'py_app:html' %}">Html Syllabus</a>
    </br>
    <a href="{% url 'py_app:css' %}">Css Syllabus</a>
    </br>
    <a href="{% url 'py_app:js' %}">Java Script Syllabus</a>
    </br>
    <a href="{% url 'sql' %}">SQL Syllabus</a> 


</body>
</html>

templates/html.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>HTML</title>
</head>
<body>
    <center>
    <h1>welcome to Html</h1>
    <a href="https://en.wikipedia.org/wiki/HTML">about Html</a>
    </center>

    <p> Select Language below :</p>
    <a href="{% url 'python' %}">Python Syllabus</a>
    </br>
    <a href="{% url 'django' %}">django Syllabus</a>
    </br>
    <a href="{% url 'py_app:css' %}">Css Syllabus</a>
    </br>
    <a href="{% url 'py_app:js' %}">Java Script Syllabus</a>
    </br>
    <a href="{% url 'sql' %}">SQL Syllabus</a> 

    
</body>
</html>

templates/js.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>JS</title>
</head>
<body>
    <center>
    <h1>welcome to Java Script</h1>
    <a href="https://en.wikipedia.org/wiki/JavaScript">about JavaScript</a>
    </center>

    <p> Select Language below :</p>
    <a href="{% url 'python' %}">Python Syllabus</a>
    </br>
    <a href="{% url 'django' %}">django Syllabus</a>
    </br>
    <a href="{% url 'py_app:html' %}">Html Syllabus</a>
    </br>
    <a href="{% url 'py_app:css' %}">Css Syllabus</a>
    </br>
    <a href="{% url 'sql' %}">SQL Syllabus</a> 
            
</body>
</html>

templates/python.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>python</title>
</head>
<body><center>
    <h1>python Syllabus</h1>
    <a href="https://en.wikipedia.org/wiki/Python_(programming_language)">about python</a>
</center>
    </br>

    <p> Select Language below :</p>
    <a href="{% url 'django' %}">Django Syllabus</a>
    </br>
    <a href="{% url 'py_app:html' %}">Html Syllabus</a>
    </br>
    <a href="{% url 'py_app:css' %}">Css Syllabus</a>
    </br>
    <a href="{% url 'py_app:js' %}">Java Script Syllabus</a>
    </br>
    <a href="{% url 'sql' %}">SQL Syllabus</a>
</body>
</html>

templates/sql.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>sql</title>
</head>
<body><center>
    <h1>welcome to SQL</h1>
    <a href="https://en.wikipedia.org/wiki/SQL">about SQL</a>
    </center>

    <p> Select Language below :</p>
    <a href="{% url 'python' %}">Python Syllabus</a>
    </br>
    <a href="{% url 'django' %}">django Syllabus</a>
    </br>
    <a href="{% url 'py_app:css' %}">Css Syllabus</a>
    </br>
    <a href="{% url 'py_app:js' %}">Java Script Syllabus</a>
    </br>
    <a href="{% url 'py_app:html' %}">Html Syllabus</a> 
</body>
</html>